# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  db:
    image: docker.io/bitnami/mariadb:11.0
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laravel
      - MARIADB_DATABASE=laravel_db
  app:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel_db
    volumes:
      - './project:/app'
    depends_on:
      - db
